### ISSUE TITLE
use Facebook Open Graph tags to set share image

### ISSUE THREAD

**Issue by liddiard** [dailybruin/caeruleum#1]
...instead of letting Facebook choose for us so awkward things [like this](https://twitter.com/sneezytaughtmee/status/575719458876080130) don't happen. 

See Facebook Developer docs: https://developers.facebook.com/docs/sharing/best-practices#tags

**Comment by blutz** [comment]
FYI there's a plugin installed called "WP Facebook Open Graph protocol" but it was disabled on 4/16/14 because it conflicted with NextGen 2.x and was causing Camayak connectivity issues. The plugin was originally installed as a quick/easy way to add Open Graph tags/images with defaults and options.

Here was my email:

> The technical details
> Turns out that NextGen 2.x has a mess of ob_start() and ob_end_flush() calls that capture the output (instead of sending it to the user) then send it later (like a buffered output string or something). The only thing is that the ob_\* functions can be nested. A single plugin might want to capture all output, process it, then output it back to the screen. The WP Facebook Open Graph protocol plugin does this — it gets the entire page, looks for title, image, and excerpt, then inserts the open graph plugins into the header.
> 
> The only problem is when these tags conflict. Since the ob_\* calls need to be queued using WP's action calls, it's pretty simple to mismatch them between plugins by different authors.
> 
> I'm guessing that's what happened here but I'm not completely sure. 
> 
> The implications
> The WP Facebook Open Graph protocol plugin definitely conflicted with NextGen 2.x so the quickest fix is to disable one of the three: Camayak, NextGen, or FB OpenGraph. 
> 
> I disabled FB Open Graph. This means the DB logo will no longer show up as an option when people post stories to their fb feeds and the default image/title might not always be right. This is the default behavior for most webpages so it shouldn't be much of an issue.
> 
> Note that this will not affect meow in any way — posts sent using meow do not depend on these tags so they'll show up how they're supposed to.

The plugins have probably updated since then but just wanted to give you a heads up to test the Camayak connection if you use the plugin.

**Comment by liddiard** [comment]
Thanks, @blutz! We'll take a look at that plugin and try to get this figured out after finals haha.

**Comment by nbedi** [comment]
RESOLVED: a1f801ab4cac5b508feb6a27e888af9be2f40125
