### ISSUE TITLE
<audio> elements don't show up

### ISSUE THREAD

**Issue by liddiard** [dailybruin/caeruleum#17]
I've tried adding a ton of styles and I can't figure out why it's not showing up: http://puu.sh/hNo5g/1f4bab491e.png

**Comment by simzou** [comment]
So it works if you embed audio like this: 

```
<audio controls style="width:100%">
     <source src="http://dailybruin.com/images/2015/05/1-Nolan-Fabricus.m4a" type="audio/mp4">
</audio>
```

and not if you do it like this:

```
<audio src="http://dailybruin.com/images/2015/05/1-Nolan-Fabricus.m4a" type="audio/mp4"></audio>
```

Not sure why since both are apparently okay by [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) but oh well
