### ISSUE TITLE
front page og:image links to flood photo

### ISSUE THREAD

**Issue by simzou** [dailybruin/caeruleum#18]
[Link](https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fdailybruin.com%2F&__mref=message_bubble)

Source of problem is [here](https://github.com/daily-bruin/caeruleum/blob/master/header.php#L58), attempting to get post thumbnail while on the front page results in the weird behavior of getting the flood image instead of not working.

**Comment by nbedi** [comment]
fixed afd3a83baf2d0cb652ad6386013b73cf1770e8f9
