### ISSUE TITLE
Weird List Error

### ISSUE THREAD

**Issue by nathanmsmith** [dailybruin/caeruleum#95]
![screen shot 2017-02-19 at 9 52 55 pm](https://cloud.githubusercontent.com/assets/5677971/23113671/9c538044-f6ee-11e6-95df-c5bfadcb1c14.png)

This shouldn't be happening 😕. I think [3c924f5](https://github.com/daily-bruin/caeruleum/commit/3c924f58295f1ce9239cced59605e031c08b85aa) is the first commit where this occurs, meaning @H-Huang introduced it? (❤️ Howard) Relevant files are probably header.php and header-default.php.

**Comment by H-Huang** [comment]
boo =( thanks for catching this @nathunsmitty. The top bar will do that when no menu is set:
![image](https://cloud.githubusercontent.com/assets/14858254/23114087/ac32ab04-f6f1-11e6-9709-d5db4d11bc62.png)

But yeah I'll change it!
There is a quick option to hide it in wordpress when no menu is set. I'll add it in with my next pull request.

**Comment by H-Huang** [comment]
had fixed this way back when, cleaning up my issues lol
